# Generated by Django 4.1.1 on 2022-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_friend_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
